project_id = "sdvyxdghxqmntyoweqbd"

[functions.notify-prospect]
verify_jwt = false

[functions.smartone-sync]
verify_jwt = false

[functions.smartone-webhook]
verify_jwt = false

[functions.sync-new-client]
verify_jwt = false
