// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://srv1182856.hstgr.cloud";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzY1MTU1MTMzLCJleHAiOjIwODA1MTUxMzN9.QtRyfpYqEw80LbxhETVievqVAlsypmxzL6EeDpF5l7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: "pkce",
  },
  realtime: {
    params: {
      eventsPerSecond: 2,
    },
    // Desabilitar realtime WebSocket para evitar erros no console durante desenvolvimento
    // quando não há necessidade de subscriptions em tempo real
    log_level: "error",
  },
  global: {
    headers: {
      "X-Client-Info": "iptv-link-web",
    },
  },
});
